<?php

return [
    'images' => [
        'navbar_logo' => [
            'group' => 'Logo website',
            'label' => 'Logo navbar (landscape)',
            'description' => 'Logo utama pada navigasi desktop.',
            'default' => 'assets/images/logo1.png',
            'recommended' => '800 × 240 px, PNG/WebP transparan',
            'contain' => true,
        ],
        'navbar_portrait_logo' => [
            'group' => 'Logo website',
            'label' => 'Logo navbar (ikon)',
            'description' => 'Logo ringkas yang tampil pada navigasi mobile.',
            'default' => 'assets/images/logo2.png',
            'recommended' => '400 × 400 px, PNG/WebP transparan',
            'contain' => true,
        ],
        'footer_logo' => [
            'group' => 'Logo website',
            'label' => 'Logo footer',
            'description' => 'Logo yang tampil pada bagian bawah website.',
            'default' => 'assets/images/logo1.png',
            'recommended' => '800 × 240 px, PNG/WebP transparan',
            'contain' => true,
        ],
        'home_about_image_left' => [
            'group' => 'Tentang kami',
            'label' => 'Tentang kami — gambar kiri',
            'description' => 'Gambar pertama pada kolase bagian Tentang kami.',
            'default' => 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=700&q=85',
            'recommended' => '900 × 1100 px',
        ],
        'home_about_image_right' => [
            'group' => 'Tentang kami',
            'label' => 'Tentang kami — gambar kanan',
            'description' => 'Gambar kedua pada kolase bagian Tentang kami.',
            'default' => 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=700&q=85',
            'recommended' => '900 × 1100 px',
        ],
        'home_impact_image' => [
            'group' => 'Dampak energi surya',
            'label' => 'Gambar utama dampak',
            'description' => 'Gambar teknisi pada bagian Dampak energi surya.',
            'default' => 'https://images.unsplash.com/photo-1605980776566-0486c3ac7617?auto=format&fit=crop&w=1000&q=85',
            'recommended' => '1200 × 900 px',
        ],
        'home_partner_avatar_1' => [
            'group' => 'Mitra teknis',
            'label' => 'Foto mitra 1',
            'description' => 'Avatar pertama pada bagian mitra teknis.',
            'default' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80',
            'recommended' => '400 × 400 px',
        ],
        'home_partner_avatar_2' => [
            'group' => 'Mitra teknis',
            'label' => 'Foto mitra 2',
            'description' => 'Avatar kedua pada bagian mitra teknis.',
            'default' => 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=120&q=80',
            'recommended' => '400 × 400 px',
        ],
        'home_partner_avatar_3' => [
            'group' => 'Mitra teknis',
            'label' => 'Foto mitra 3',
            'description' => 'Avatar ketiga pada bagian mitra teknis.',
            'default' => 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=120&q=80',
            'recommended' => '400 × 400 px',
        ],
        'home_partner_avatar_4' => [
            'group' => 'Mitra teknis',
            'label' => 'Foto mitra 4',
            'description' => 'Avatar keempat pada bagian mitra teknis.',
            'default' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=120&q=80',
            'recommended' => '400 × 400 px',
        ],
        'home_service_solar_rumah' => [
            'group' => 'Kartu layanan',
            'label' => 'Layanan Solar Rumah',
            'description' => 'Gambar kartu layanan Solar Rumah.',
            'default' => 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1800&q=85',
            'recommended' => '1200 × 900 px',
        ],
        'home_service_solar_industri' => [
            'group' => 'Kartu layanan',
            'label' => 'Layanan Solar Industri',
            'description' => 'Gambar kartu layanan Solar Industri.',
            'default' => 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1800&q=85',
            'recommended' => '1200 × 900 px',
        ],
        'home_service_plts_hybrid' => [
            'group' => 'Kartu layanan',
            'label' => 'Layanan PLTS Hybrid',
            'description' => 'Gambar kartu layanan PLTS Hybrid.',
            'default' => 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1800&q=85',
            'recommended' => '1200 × 900 px',
        ],
        'home_service_off_grid' => [
            'group' => 'Kartu layanan',
            'label' => 'Layanan Off-Grid',
            'description' => 'Gambar kartu layanan Off-Grid.',
            'default' => 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1800&q=85',
            'recommended' => '1200 × 900 px',
        ],
        'home_service_on_grid' => [
            'group' => 'Kartu layanan',
            'label' => 'Layanan On-Grid',
            'description' => 'Gambar kartu layanan On-Grid.',
            'default' => 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=1800&q=85',
            'recommended' => '1200 × 900 px',
        ],
        'home_service_bess' => [
            'group' => 'Kartu layanan',
            'label' => 'Layanan BESS',
            'description' => 'Gambar kartu layanan BESS.',
            'default' => 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1800&q=85',
            'recommended' => '1200 × 900 px',
        ],
        'home_why_image' => [
            'group' => 'Mengapa Luma Daya',
            'label' => 'Gambar Mengapa Luma Daya',
            'description' => 'Gambar besar pada bagian Mengapa Luma Daya.',
            'default' => 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1000&q=85',
            'recommended' => '1200 × 1000 px',
        ],
        'home_benefit_savings' => [
            'group' => 'Manfaat utama',
            'label' => 'Hemat tagihan listrik',
            'description' => 'Gambar kartu manfaat Hemat tagihan listrik.',
            'default' => 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=600&q=85',
            'recommended' => '800 × 1000 px',
        ],
        'home_benefit_maintenance' => [
            'group' => 'Manfaat utama',
            'label' => 'Perawatan rendah',
            'description' => 'Gambar kartu manfaat Perawatan rendah.',
            'default' => 'https://images.unsplash.com/photo-1548611716-3000815a5803?auto=format&fit=crop&w=600&q=85',
            'recommended' => '800 × 1000 px',
        ],
        'home_benefit_monitoring' => [
            'group' => 'Manfaat utama',
            'label' => 'Pemantauan mudah',
            'description' => 'Gambar kartu manfaat Pemantauan mudah.',
            'default' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=600&q=85',
            'recommended' => '800 × 1000 px',
        ],
        'home_benefit_environment' => [
            'group' => 'Manfaat utama',
            'label' => 'Ramah lingkungan',
            'description' => 'Gambar kartu manfaat Ramah lingkungan.',
            'default' => 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=85',
            'recommended' => '800 × 1000 px',
        ],
    ],
];
