<?php

return [
    'solutions' => [
        'solar-rumah' => [
            'name' => 'Solar Rumah',
            'label' => 'Solar Rumah',
            'title' => 'Solar Rumah untuk Hunian | Luma Daya',
            'description' => 'Solusi panel surya rumah dari Luma Daya untuk menghemat tagihan listrik, meningkatkan nilai properti, dan memantau produksi energi harian.',
            'hero_image' => 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1800&q=85',
            'kicker' => 'PLTS atap rumah',
            'headline' => 'Solar rumah yang rapi, hemat, dan mudah dipantau.',
            'intro' => 'Luma Daya merancang sistem panel surya rumah sesuai pola pemakaian listrik, kondisi atap, kapasitas daya PLN, dan target penghematan keluarga.',
            'audience' => 'Pemilik rumah, cluster perumahan, villa, dan rumah usaha yang ingin menurunkan biaya listrik bulanan.',
            'benefits' => [
                'Mengurangi tagihan listrik siang hari',
                'Desain sistem sesuai luas dan arah atap',
                'Pemantauan produksi energi dari aplikasi',
                'Instalasi rapi dengan standar keselamatan',
            ],
            'process' => [
                'Audit tagihan dan pola pemakaian listrik',
                'Survei atap, panel listrik, dan potensi bayangan',
                'Desain kapasitas PLTS dan estimasi penghematan',
                'Instalasi, pengujian, dan edukasi penggunaan',
            ],
            'faq' => [
                ['Berapa kapasitas solar rumah yang ideal?', 'Kapasitas ideal tergantung pemakaian bulanan, daya listrik terpasang, luas atap, dan target penghematan. Tim kami menghitungnya dari data tagihan dan survei lokasi.'],
                ['Apakah solar rumah tetap terhubung PLN?', 'Umumnya sistem rumah memakai skema on-grid atau hybrid, sehingga tetap bisa memakai listrik PLN saat produksi panel tidak cukup.'],
                ['Apakah atap perlu direnovasi?', 'Tidak selalu. Kami memeriksa kekuatan atap, arah, kemiringan, dan area bayangan sebelum merekomendasikan desain pemasangan.'],
            ],
        ],
        'solar-industri' => [
            'name' => 'Solar Industri',
            'label' => 'Solar Industri',
            'title' => 'Solar Industri untuk Pabrik dan Gudang | Luma Daya',
            'description' => 'PLTS industri untuk pabrik, gudang, cold storage, dan fasilitas komersial yang ingin menurunkan biaya energi dan emisi operasional.',
            'hero_image' => 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1800&q=85',
            'kicker' => 'PLTS komersial dan industri',
            'headline' => 'Solar industri untuk beban listrik besar dan operasional jangka panjang.',
            'intro' => 'Kami membantu bisnis merancang PLTS atap dan lahan untuk fasilitas industri dengan analisis beban, profil produksi, keselamatan instalasi, dan proyeksi pengembalian investasi.',
            'audience' => 'Pabrik, gudang, kawasan industri, cold storage, hotel, sekolah, rumah sakit, dan gedung komersial.',
            'benefits' => [
                'Menekan biaya listrik operasional',
                'Mendukung target ESG dan dekarbonisasi',
                'Pemantauan performa multi-inverter',
                'Desain sesuai standar keselamatan industri',
            ],
            'process' => [
                'Analisis load profile dan tagihan listrik bisnis',
                'Survei struktur atap, panel distribusi, dan jalur kabel',
                'Simulasi produksi energi dan estimasi ROI',
                'Instalasi bertahap untuk meminimalkan gangguan operasional',
            ],
            'faq' => [
                ['Apakah PLTS industri mengganggu produksi?', 'Pekerjaan direncanakan bertahap dan disesuaikan dengan jam operasional agar gangguan terhadap produksi tetap minimal.'],
                ['Apa data yang dibutuhkan untuk estimasi awal?', 'Biasanya kami membutuhkan tagihan listrik, single line diagram bila tersedia, luas atap atau lahan, dan informasi pola operasional.'],
                ['Apakah bisa dipantau oleh tim fasilitas?', 'Bisa. Sistem pemantauan dapat menampilkan produksi energi, performa inverter, dan peringatan agar tim fasilitas cepat merespons anomali.'],
            ],
        ],
        'plts-hybrid' => [
            'name' => 'PLTS Hybrid',
            'label' => 'PLTS Hybrid',
            'title' => 'PLTS Hybrid dengan Baterai dan PLN | Luma Daya',
            'description' => 'Sistem PLTS hybrid yang menggabungkan panel surya, baterai, PLN, dan genset untuk menjaga pasokan listrik lebih stabil.',
            'hero_image' => 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1800&q=85',
            'kicker' => 'Surya, baterai, PLN, genset',
            'headline' => 'PLTS hybrid untuk listrik yang lebih fleksibel dan tangguh.',
            'intro' => 'PLTS hybrid cocok untuk lokasi yang butuh penghematan sekaligus cadangan daya. Sistem dapat mengatur prioritas energi dari panel surya, baterai, PLN, atau genset.',
            'audience' => 'Rumah besar, villa, klinik, resort, fasilitas terpencil, dan bisnis yang membutuhkan cadangan daya saat listrik padam.',
            'benefits' => [
                'Cadangan daya saat listrik PLN padam',
                'Penggunaan energi surya lebih maksimal',
                'Bisa dikombinasikan dengan genset',
                'Kontrol prioritas pemakaian energi',
            ],
            'process' => [
                'Analisis beban prioritas dan durasi cadangan daya',
                'Perhitungan kapasitas panel, inverter, dan baterai',
                'Desain mode operasi hybrid',
                'Pengujian skenario normal, cadangan daya, dan pemulihan',
            ],
            'faq' => [
                ['Apa beda PLTS hybrid dan on-grid?', 'On-grid fokus sinkron dengan PLN tanpa baterai utama, sedangkan hybrid menambahkan baterai atau sumber cadangan untuk fleksibilitas dan daya cadangan.'],
                ['Apakah PLTS hybrid bisa memakai genset?', 'Bisa. Sistem dapat didesain agar genset menjadi sumber cadangan tambahan saat baterai rendah atau beban sedang tinggi.'],
                ['Apakah cocok untuk rumah?', 'Cocok untuk rumah yang membutuhkan cadangan listrik, terutama jika ada perangkat penting seperti pompa, jaringan internet, kulkas, atau peralatan kerja.'],
            ],
        ],
        'off-grid' => [
            'name' => 'Off-Grid',
            'label' => 'Off-Grid',
            'title' => 'PLTS Off-Grid untuk Lokasi Tanpa PLN | Luma Daya',
            'description' => 'PLTS off-grid mandiri untuk lokasi terpencil, kebun, tambak, BTS, pos operasional, dan bangunan yang belum terjangkau jaringan PLN.',
            'hero_image' => 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1800&q=85',
            'kicker' => 'Energi mandiri tanpa jaringan PLN',
            'headline' => 'PLTS off-grid untuk lokasi yang membutuhkan listrik mandiri.',
            'intro' => 'Sistem off-grid dirancang agar panel surya dan baterai mampu menyuplai beban penting tanpa ketergantungan pada jaringan PLN.',
            'audience' => 'Kebun, tambak, pulau kecil, basecamp proyek, BTS, pos penjagaan, dan fasilitas pedesaan.',
            'benefits' => [
                'Tidak bergantung pada jaringan PLN',
                'Mengurangi penggunaan BBM genset',
                'Baterai disesuaikan durasi otonomi',
                'Cocok untuk beban penting 24 jam',
            ],
            'process' => [
                'Inventarisasi beban listrik harian',
                'Perhitungan energi, baterai, dan hari otonomi',
                'Desain proteksi sistem dan panel distribusi',
                'Instalasi serta pelatihan perawatan dasar',
            ],
            'faq' => [
                ['Apakah off-grid bisa hidup 24 jam?', 'Bisa jika kapasitas panel dan baterai didesain sesuai total beban harian, cuaca, serta kebutuhan hari otonomi.'],
                ['Apakah genset masih diperlukan?', 'Untuk beban kritis, genset cadangan dapat disiapkan sebagai sumber tambahan saat cuaca buruk berkepanjangan.'],
                ['Apa yang paling penting dalam desain off-grid?', 'Data beban listrik yang akurat sangat penting karena kapasitas baterai dan panel ditentukan dari kebutuhan energi harian.'],
            ],
        ],
        'on-grid' => [
            'name' => 'On-Grid',
            'label' => 'On-Grid',
            'title' => 'PLTS On-Grid Terhubung PLN | Luma Daya',
            'description' => 'Sistem PLTS on-grid untuk rumah dan bisnis yang ingin menghemat pemakaian listrik siang hari dengan panel surya terhubung jaringan PLN.',
            'hero_image' => 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=1800&q=85',
            'kicker' => 'Panel surya terhubung PLN',
            'headline' => 'PLTS on-grid untuk efisiensi listrik harian.',
            'intro' => 'PLTS on-grid menghasilkan listrik dari panel surya saat siang hari dan bekerja bersama jaringan PLN. Sistem ini populer untuk rumah, kantor, dan fasilitas bisnis.',
            'audience' => 'Rumah tinggal, kantor, ruko, sekolah, hotel, gudang, dan fasilitas komersial dengan beban siang cukup tinggi.',
            'benefits' => [
                'Investasi awal lebih efisien dibanding sistem baterai',
                'Cocok untuk beban listrik siang hari',
                'Pemantauan produksi energi real-time',
                'Desain sederhana dan perawatan relatif rendah',
            ],
            'process' => [
                'Analisis konsumsi listrik dan daya PLN',
                'Perhitungan kapasitas panel dan inverter',
                'Instalasi PLTS terhubung panel distribusi',
                'Pengujian sinkronisasi dan pemantauan sistem',
            ],
            'faq' => [
                ['Apakah on-grid menyimpan listrik?', 'Sistem on-grid standar tidak menyimpan energi karena tidak memakai baterai utama. Jika butuh cadangan daya, pertimbangkan sistem hybrid.'],
                ['Apakah tetap bisa memakai PLN?', 'Ya. Saat produksi panel kurang, beban listrik tetap dipenuhi dari jaringan PLN.'],
                ['Untuk siapa sistem on-grid paling cocok?', 'Paling cocok untuk pengguna dengan aktivitas listrik tinggi pada siang hari, seperti rumah aktif, kantor, ruko, dan pabrik.'],
            ],
        ],
        'bess' => [
            'name' => 'BESS',
            'label' => 'BESS',
            'title' => 'BESS Sistem Penyimpanan Energi Baterai | Luma Daya',
            'description' => 'Solusi BESS untuk penyimpanan energi, pengurangan beban puncak, cadangan daya, integrasi PLTS, dan stabilitas operasional fasilitas komersial atau industri.',
            'hero_image' => 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1800&q=85',
            'kicker' => 'Sistem penyimpanan energi baterai',
            'headline' => 'BESS untuk penyimpanan energi dan keandalan daya.',
            'intro' => 'BESS membantu menyimpan energi, menjaga pasokan listrik, mengurangi beban puncak, dan meningkatkan pemanfaatan energi surya.',
            'audience' => 'Fasilitas industri, gedung komersial, microgrid, pusat data kecil, resort, dan lokasi dengan kebutuhan cadangan daya atau pengurangan beban puncak.',
            'benefits' => [
                'Cadangan daya untuk beban prioritas',
                'Pengurangan beban puncak untuk efisiensi operasional',
                'Meningkatkan pemanfaatan energi PLTS',
                'Pemantauan baterai dan performa sistem',
            ],
            'process' => [
                'Analisis profil beban dan kebutuhan cadangan daya',
                'Sizing kapasitas baterai, PCS, dan proteksi',
                'Integrasi dengan PLTS, PLN, atau genset',
                'Pengujian akhir, pemantauan, dan rencana perawatan',
            ],
            'faq' => [
                ['Apa fungsi utama BESS?', 'BESS menyimpan energi listrik untuk digunakan saat dibutuhkan, misalnya saat beban puncak, listrik padam, atau produksi PLTS sedang rendah.'],
                ['Apakah BESS harus digabung dengan PLTS?', 'Tidak harus, tetapi BESS sangat efektif bila digabung dengan PLTS karena energi surya dapat disimpan dan digunakan lebih fleksibel.'],
                ['Bagaimana menentukan kapasitas BESS?', 'Kapasitas ditentukan dari tujuan sistem, profil beban, durasi cadangan daya, batas daya puncak, dan strategi operasional fasilitas.'],
            ],
        ],
    ],
];
